version: '3'
services:
  postgres:
    container_name: graphql-db
    image: postgres:14.2
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      DATABASE_URL: postgresql://prisma:prisma@localhost:5432/graphql-db
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: